### ISSUE TITLE
NRSC5 decoding now possible

### ISSUE THREAD

**Issue by BrodieBruce901** [philburr/hdradio#2]
I've been following your project for the past few months and have been checking on the progress. While looking around yesterday I discovered someone has been able to decode audio from nrsc5 streams. I wanted to let you know if you were not aware. The project is here: https://github.com/theori-io/nrsc5

**Comment by philburr** [comment]
I've already started taking a look at it.  I'm not sure whether to do anything more with this project or to start enhancing that one.

**Comment by BrodieBruce901** [comment]
Either way it's great a very complicated piece of the puzzle has been solved. I look forward to seeing what comes from the research of these projects.

**Comment by BrodieBruce901** [comment]
The biggest feature that NRSC5 could use right now is the ability to multithread. I'd love to use it on my Rockchip based laptop but a 1.8 GHz single core is not enough to run it.
